### ISSUE TITLE
Concentration Values change with Granularity

### ISSUE THREAD

**Issue by apoorvagnihotri** [sandialabs/chama#21]
Running the code below with values of ``granularity`` to be ``40`` and ``100`` gives different concentration values in `chama.simulation.GaussianPlume` model. ``granularity`` below is a variable that tells how much finely we want to divide the volume. 

**Expected Output**:
Similar concentration values, irrespective of the value of ``granularity``.

**Current Output**:
Radically different values by just changing the granularity. I was able to get the max concentration values to be equal to ``S = 389.843737`` for the case when ``granularity = 100``
And ``S = 48.59`` when ``granularity = 40``.

``` python
# %% Imports
import numpy as np
import pandas as pd
import chama
import matplotlib.pyplot as plt
#%matplotlib inline

# %% Making a 3D grid
x_vals = (0, 40)
y_vals = x_vals
z_vals = (0, 10)
x_start = 10
y_start = x_start
z_start = 5
granularity = 40  ######### ←← Just changing this makes the concentration values fluctuate
x_grid = np.linspace(*x_vals, granularity) # this is in mts
y_grid = np.linspace(*y_vals, granularity)
z_grid = np.linspace(*z_vals, granularity)
grid = chama.simulation.Grid(x_grid, y_grid, z_grid)

# %% Defining a pollutant source with rate
source = chama.simulation.Source(x_start, y_start, z_start, rate = 3)

# %% Defining the Atmospheric Conditions (We only support x-y plane air movement)
atm = pd.DataFrame(
        {
           'Wind Direction': [45],
           'Wind Speed': [2],
           'Stability Class': ['A'],
        },
        index=[0]
      )

# %% Gives the concentrations during steady state
gauss_plume = chama.simulation.GaussianPlume(grid, source, atm)
gauss_plume.run()
signal = gauss_plume.conc
print(signal.head(5))
print(signal.tail(5))

# %%
chama.graphics.signal_convexhull(
        signal, 
        scenarios=['S'], 
        threshold=1e-5,
        x_range = x_vals, 
        y_range = y_vals, 
        z_range = z_vals
    )
print (signal.max())
plt.show()
```

I was hoping the value of the concentrations should not fluctuate. Is there something that I am missing here?

Thanks a lot for the help.

**Comment by kaklise** [comment]
I believe you are seeing a change in max concentration based on the distance of the nearest grid cell to the source.  When you use granularity of 100, the nearest grid cell is very close to the source and concentration at that point is high.  As the granularity decreases, the nearest grid cell to the source is further away and has a lower concentration.  If you look concentration across the entire region, changes in granularity has a smaller impact on the results.  Unfortunately, statistics like max or mean are not good at picking this up.  I suggest looking at a cross section of the signal,  `chama.graphics.signal_xsection(signal, 'S', x_value=40,y_value=40)` .

**Comment by apoorvagnihotri** [comment]
Thanks a lot for your help.
