### ISSUE TITLE
Importing an EPANET network defined in INP file format

### ISSUE THREAD

**Issue by pirofti** [sandialabs/chama#27]
Hi,

Is there an example somewhere about importing an INP file (defining a water network) to be used by Chama?

The closest I could find is [test_examples.py](chama/tests/test_examples.py) that reads from a [csv](chama/tests/data/signals.csv) file. I would like to do the same, but from an INP file like

Please note that this issue is not just about file formats, but also about the [data within the INP](https://epanet22.readthedocs.io/en/latest/11_importing_exporting.html#importing-a-partial-network) that might be different from the CSV data given in the example above. For an example, check out the benchmark [Hanoi network INP](https://github.com/pirofti/ddnet-online/blob/master/networks/hanoi.inp) description here.

Thank you,
Paul Irofti

**Comment by kaklise** [comment]
We have included an example that uses Chama with a water network model (loaded from an INP file) in the WNTR software package.  You can find that example at https://github.com/USEPA/WNTR/blob/master/examples/sensor_placement.py.  I should update the Chama documentation to link to that example.

**Comment by pirofti** [comment]
Wow, thank you for the blazing fast reply!

I think that example is exactly what I was looking for and it would be great, indeed, if you could add a link to it in the documentation.

All the best,
Paul
